### ISSUE TITLE
Please fix your sample code

### ISSUE THREAD

**Issue by ahmadarif** [ntvsx193/adonis-spreadsheet#1]
Your code is
`const ss = new SpreadSheet(request, params.format)`

It should be
`const ss = new SpreadSheet(response, params.format)`

**Comment by ntvsx193** [comment]
Thx!
Fixed in https://github.com/ntvsx193/adonis-spreadsheet/commit/13742817d57d4393801fdd3ce103f6cb7f1eb517

**Comment by ahmadarif** [comment]
Mancaaps, you're welcome :D
