### ISSUE TITLE
Merge Cells

### ISSUE THREAD

**Issue by GusMartins499** [ntvsx193/adonis-spreadsheet#4]
Hi guys, its possible to merge cells ?

Example:

![image](https://user-images.githubusercontent.com/43645525/128034439-9dd504b4-801b-4300-90b1-6933ba22f8c4.png)

**Comment by ntvsx193** [comment]
Try use https://docs.sheetjs.com/#worksheet-object

**Comment by GusMartins499** [comment]
> Try use https://docs.sheetjs.com/#worksheet-object

Thanks, i'm close this issue
